# Generated by Django 5.2.4 on 2025-07-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('teacher', '0001_initial'),
        ('teacher_subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(through='teacher_subject.TeacherSubject', to='subjects.subject'),
        ),
    ]
