# Generated by Django 5.2.4 on 2025-07-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(blank=True, choices=[('Assistant Teacher', 'Assistant Teacher'), ('Senior Teacher', 'Senior Teacher'), ('Head Teacher', 'Head Teacher'), ('Subject Teacher', 'Subject Teacher'), ('ICT Teacher', 'ICT Teacher'), ('Physical Education Teacher', 'Physical Education Teacher'), ('Library Teacher', 'Library Teacher'), ('Art & Craft Teacher', 'Art & Craft Teacher'), ('Lecturer', 'Lecturer'), ('Senior Lecturer', 'Senior Lecturer'), ('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor'), ('Principal', 'Principal'), ('Vice Principal', 'Vice Principal')], max_length=100, null=True),
        ),
    ]
