# Generated by Django 5.2.4 on 2025-07-25 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
                ('medium', models.CharField(choices=[('bangla', 'Bangla Medium'), ('english', 'English Medium')], max_length=10)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='school_class.schoolclass')),
            ],
            options={
                'unique_together': {('school_class', 'name')},
            },
        ),
    ]
