# Generated by Django 5.2.4 on 2025-07-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_class', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='classes',
            field=models.ManyToManyField(to='school_class.schoolclass'),
        ),
    ]
